version: "3.7"

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
  alertmanager:
    image: prom/alertmanager:latest
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - "./alertmanager:/config"
      - alertmanager-data:/data
    command: --config.file=/config/alertmanager.yml --log.level=debug
  genesys_exporter:
    image: genesys_exporter:latest
    ports:
      - 2113:2113
    environment:
      GENESYSCLOUD_REGION: ${GENESYSCLOUD_REGION}
      GENESYSCLOUD_OAUTHCLIENT_ID: ${GENESYSCLOUD_OAUTHCLIENT_ID}
      GENESYSCLOUD_OAUTHCLIENT_SECRET: ${GENESYSCLOUD_OAUTHCLIENT_SECRET}

volumes:
  prometheus-data:

  grafana-data:

  alertmanager-data:
