route:
  group_by: ["alertname"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: "pager-duty"
receivers:
  - name: "pager-duty"
    pagerduty_configs:
      - service_key: "<INTEGRATION KEY>"
