groups:
  - name: low_mos_score
    rules:
      - alert: MOS Score below average
        expr: genesys_mos_score <= 4.873
        for: 1m
        labels:
          severity: page
        annotations:
          summary: "conversation {{ $labels.conversationId }} call quality was bad"
